[package]
name = "fdkaac-sys"
version = "0.1.6"
authors = ["luozijun <luozijun.assistant@gmail.com>"]
edition = "2018"
links = "fdk-aac"
build = "build.rs"

[dependencies]


[build-dependencies]
bindgen = "0.40"
pkg-config = "0.3"
